### ISSUE TITLE
 UncaughtException: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Collection;Ljava/util/Collection;Lcom/facebook/AccessTokenSource;Ljava/util/Date;Ljava/util/Date;)V in class Lcom/facebook/AccessToken; or its super classes (declaration of 'com.facebook.AccessToken' 

### ISSUE THREAD

**Issue by hoffergg** [hoffergg/Android-Issues#2]

**Comment by hoffergg** [comment]
2018-11-17 12:42:23.152 11565-12811/com.socxxxial.xxx E/UncaughtException: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Collection;Ljava/util/Collection;Lcom/facebook/AccessTokenSource;Ljava/util/Date;Ljava/util/Date;)V in class Lcom/facebook/AccessToken; or its super classes (declaration of 'com.facebook.AccessToken' appears in /data/app/com.xxx.xxx-eqmp3QC1oLGU8m_HSZ_e7w==/split_lib_dependencies_apk.apk)
        at com.parse.FacebookController.setAuthData(FacebookController.java:163)
        at com.parse.ParseFacebookUtils$1.onRestore(ParseFacebookUtils.java:113)
        at com.parse.ParseAuthenticationManager$2.call(ParseAuthenticationManager.java:70)
        at com.parse.ParseAuthenticationManager$2.call(ParseAuthenticationManager.java:67)
        at bolts.Task$4.run(Task.java:357)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by hoffergg** [comment]
ParseFacebookUtil 和 facebook sdk 版本不匹配

implementation 'com.parse:parsefacebookutils-v4-android:1.10.3@aar'
implementation 'com.facebook.android:facebook-android-sdk:4.30.0'
